version: "3.3"

services:
  goody:
    build: ./goody
    command: sh ./entrypoint.sh
    ports:
      - 1324:1323
    volumes:
      - ./goody:/app
      - type: bind
        source: ./goody.sh
        target: /app/entrypoint.sh
    working_dir: /app
    depends_on:
      - keycloak

  gouser:
    build: ./gouser
    command: sh ./entrypoint.sh
    ports:
      - 1323:1323
    volumes:
      - ./gouser:/app
      - type: bind
        source: ./gouser.sh
        target: /app/entrypoint.sh
    working_dir: /ap
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8082:8080


  api-gateway:
    image: nginx
    volumes:
      - ./nginx-service:/etc/nginx/conf.d
    restart: always
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - goody
      - gouser
      - keycloak